name: SonarCloud analysis
description: Run SonarCloud analysis using the official action
inputs:
  project_key:
    description: SonarCloud project key
    required: true
  project_name:
    description: SonarCloud project name
    required: true
  organization:
    description: SonarCloud organization
    required: true
    default: sk-solar-project
  token_secret_name:
    description: Name of the GitHub secret containing the Sonar token
    required: false
    default: SONAR_TOKEN

runs:
  using: composite
  steps:
    - name: SonarCloud scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.project_key }}
          -Dsonar.projectName=${{ inputs.project_name }}
          -Dsonar.organization=${{ inputs.organization }}