name: Terraform apply
description: Run terraform init, plan, and apply in a directory
inputs:
  working_dir:
    description: Path to the Terraform configuration directory
    required: true
  plan_file:
    description: Plan file name
    required: false
    default: tfplan

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: terraform init

    - name: Terraform plan
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: terraform plan -out=${{ inputs.plan_file }}

    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: terraform apply -auto-approve ${{ inputs.plan_file }}